#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-install
Version  : 1.3.4
Release  : 1
URL      : https://files.pythonhosted.org/packages/ae/d4/ee70b7404154ac95b76b5125e9713ec3f2c9a91c366d90dedf059c75cec3/install-1.3.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/ae/d4/ee70b7404154ac95b76b5125e9713ec3f2c9a91c366d90dedf059c75cec3/install-1.3.4.tar.gz
Summary  : UNKNOWN
Group    : Development/Tools
License  : MIT
Requires: python-install-python = %{version}-%{release}
Requires: python-install-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
A package to install pip packages from within code.
        
        Requires Python 2.7+, 3.5+

%package python
Summary: python components for the python-install package.
Group: Default
Requires: python-install-python3 = %{version}-%{release}

%description python
python components for the python-install package.


%package python3
Summary: python3 components for the python-install package.
Group: Default
Requires: python3-core
Provides: pypi(python_install)

%description python3
python3 components for the python-install package.


%prep
%setup -q -n install-1.3.4
cd %{_builddir}/install-1.3.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636494689
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
